# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "cron"
      cronjob: "0 0 25 * *"
    commit-message:
      prefix: "chore(deps): "
    target-branch: "main"
    open-pull-requests-limit: 5
    groups:
      # one PR for all
      all:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 25 * *"
    commit-message:
      prefix: "chore(deps): "
    open-pull-requests-limit: 5
    groups:
      # one PR for all
      all:
        patterns:
          - "*"
    cooldown:
      default-days: 7
